---
- name: Install System Dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  loop:
    - curl
    - wget
    - git
    - build-essential
    - cmake
    - pkg-config
    - python3
    - python3-pip
    - python3-dev
    - python3-venv
    - ruby
    - ruby-rubygems
    - ruby-dev
    - libssl-dev
    - libffi-dev
    - libpcap-dev
    - libsqlite3-dev
    - zlib1g-dev
    - mingw-w64
    - nasm
    - golang-go
    - openjdk-17-jdk
    - tmux
    - net-tools
    - dnsutils
